kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cka-lab-95
networking:
  ipFamily: ipv4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./course
        containerPath: /opt/course/95
  - role: worker
