apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operator-prod

resources:
- ../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: operator
      labels:
        project_id: prod_7768e94e-88da-4744-9135-f1e7fbb96daf
  target:
    kind: Deployment
    name: operator
