apiVersion: v1
kind: Namespace
metadata:
  name: project-c13
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: o3db
  namespace: project-c13
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  serviceName: o3db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
