kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cka-lab-6
networking:
  ipFamily: ipv4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/cka6-data
    containerPath: /Volumes/Data
