apiVersion: v1
kind: Namespace
metadata:
  name: project-h800
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: o3db
  namespace: project-h800
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  serviceName: o3db
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
